#!/bin/sh
set -e

CONFIG_PATH="${FELIZ_CONFIG_PATH:-${HOME}/.feliz/feliz.yml}"

# --- Preflight checks ---
echo "Feliz preflight checks..."

check_tool() {
  if command -v "$1" >/dev/null 2>&1; then
    echo "  [OK] $1 found: $($1 --version 2>&1 | head -1)"
  else
    echo "  [WARN] $1 not found"
  fi
}

check_tool bun
check_tool git
check_tool gh

# Check at least one agent CLI
AGENT_FOUND=0
if command -v claude >/dev/null 2>&1; then
  echo "  [OK] claude found"
  AGENT_FOUND=1
fi
if command -v codex >/dev/null 2>&1; then
  echo "  [OK] codex found"
  AGENT_FOUND=1
fi
if [ "$AGENT_FOUND" -eq 0 ]; then
  echo "  [WARN] No agent CLI found (claude or codex). Install one or set ANTHROPIC_API_KEY / OPENAI_API_KEY."
fi

# Check GitHub CLI auth and token scope
if command -v gh >/dev/null 2>&1; then
  if gh auth status >/dev/null 2>&1; then
    echo "  [OK] gh authenticated"
    # Verify token has repo access by checking scopes
    TOKEN_SCOPES=$(gh api -i user 2>/dev/null | grep -i "x-oauth-scopes:" | head -1 || true)
    if [ -n "$TOKEN_SCOPES" ]; then
      if echo "$TOKEN_SCOPES" | grep -qi "repo"; then
        echo "  [OK] GITHUB_TOKEN has 'repo' scope"
      else
        echo "  [WARN] GITHUB_TOKEN may be missing 'repo' scope. PR creation requires it."
        echo "         Scopes found:$TOKEN_SCOPES"
      fi
    fi
  else
    if [ -n "$GITHUB_TOKEN" ] || [ -n "$GH_TOKEN" ]; then
      echo "  [OK] gh will authenticate via GITHUB_TOKEN/GH_TOKEN env var"
    else
      echo "  [WARN] gh not authenticated. Set GITHUB_TOKEN or run 'gh auth login'."
    fi
  fi
fi

# Check required env vars
if [ -z "$LINEAR_OAUTH_TOKEN" ]; then
  echo "  [WARN] LINEAR_OAUTH_TOKEN not set. Run 'feliz auth linear' to authenticate."
fi
if [ -z "$GITHUB_TOKEN" ] && [ -z "$GH_TOKEN" ]; then
  echo "  [WARN] GITHUB_TOKEN not set. GitHub operations (PR creation) will fail."
  echo "         Create a token with 'repo' scope at https://github.com/settings/tokens"
fi
if [ -z "$GIT_AUTHOR_NAME" ]; then
  echo "  [WARN] GIT_AUTHOR_NAME not set. Commits will use system default."
fi
if [ -z "$GIT_AUTHOR_EMAIL" ]; then
  echo "  [WARN] GIT_AUTHOR_EMAIL not set. Commits will use system default."
fi

echo ""

# --- Auto-generate config if none exists ---
if [ ! -f "$CONFIG_PATH" ]; then
  echo "No config found at $CONFIG_PATH. Generating from environment..."
  mkdir -p "$(dirname "$CONFIG_PATH")"
  cat > "$CONFIG_PATH" <<YAML
# Auto-generated by docker-entrypoint.sh
linear:
  oauth_token: \$LINEAR_OAUTH_TOKEN

webhook:
  port: 3421

storage:
  data_dir: /data/feliz
  workspace_root: /data/feliz/workspaces

agent:
  default: claude-code

projects: []
YAML
  echo "Config written to $CONFIG_PATH"
  echo ""
  echo "Next steps:"
  echo "  1. Add a project:  docker compose exec feliz bun run src/cli/index.ts project add"
  echo "  2. Or run auth:    docker compose exec feliz bun run src/cli/index.ts auth linear"
  echo ""
fi

# --- Validate config ---
echo "Validating configuration..."
if bun run src/cli/index.ts config validate --config "$CONFIG_PATH"; then
  echo ""
else
  echo ""
  echo "[WARN] Config validation failed. The daemon will start but may encounter errors."
  echo ""
fi

# --- Run the requested command ---
# --config before $@ so user-provided --config overrides the default
exec bun run src/cli/index.ts --config "$CONFIG_PATH" "$@"
